services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:17
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - ADMIN_PASSWD=admin   # master password for DB creation
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
      - ./custom_addons:/mtn/custom-addons   # fixed path

volumes:
  db-data:
